Traceback (most recent call last):
  File "/home/pranavsatheesh/host_galaxies/py_files/population_sort_by_mergers.py", line 495, in <module>
    pop_gen = population_generator_for_brahma(basePath,merger_file_path)
  File "/home/pranavsatheesh/host_galaxies/py_files/population_sort_by_mergers.py", line 315, in __init__
    self.mrg_file = h5py.File(self.merger_file_path, 'r')
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/h5py/_hl/files.py", line 561, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = '/home/pranavsatheesh/host_galaxies/data/merger_files/galaxy-mergers_brahma__gas-000_dm-000_star-010_bh-001.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Traceback (most recent call last):
  File "/home/pranavsatheesh/host_galaxies/py_files/population_sort_by_mergers.py", line 495, in <module>
    pop_gen = population_generator_for_brahma(basePath,merger_file_path)
  File "/home/pranavsatheesh/host_galaxies/py_files/population_sort_by_mergers.py", line 315, in __init__
    self.mrg_file = h5py.File(self.merger_file_path, 'r')
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/h5py/_hl/files.py", line 561, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = '/home/pranavsatheesh/host_galaxies/data/merger_files/galaxy-mergers_brahma__gas-000_dm-000_star-010_bh-001.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Traceback (most recent call last):
  File "/home/pranavsatheesh/host_galaxies/py_files/population_sort_by_mergers.py", line 495, in <module>
    pop_gen = population_generator_for_brahma(basePath,merger_file_path)
  File "/home/pranavsatheesh/host_galaxies/py_files/population_sort_by_mergers.py", line 315, in __init__
    self.mrg_file = h5py.File(self.merger_file_path, 'r')
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/h5py/_hl/files.py", line 561, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = '/home/pranavsatheesh/host_galaxies/data/merger_files/galaxy-mergers_brahma__gas-000_dm-000_star-010_bh-001.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Traceback (most recent call last):
  File "/home/pranavsatheesh/host_galaxies/py_files/population_sort_by_mergers.py", line 495, in <module>
    pop_gen = population_generator_for_brahma(basePath,merger_file_path)
  File "/home/pranavsatheesh/host_galaxies/py_files/population_sort_by_mergers.py", line 315, in __init__
    self.mrg_file = h5py.File(self.merger_file_path, 'r')
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/h5py/_hl/files.py", line 561, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = '/home/pranavsatheesh/host_galaxies/data/merger_files/galaxy-mergers_brahma__gas-000_dm-000_star-010_bh-001.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
