Traceback (most recent call last):
  File "/home/pranavsatheesh/host_galaxies/py_files/create_control_sample.py", line 65, in <module>
    write_control_sample(control_sample, pop_file_loc)
  File "/home/pranavsatheesh/host_galaxies/py_files/create_control_sample.py", line 55, in write_control_sample
    f.create_dataset(key, data=value)
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/h5py/_hl/group.py", line 183, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/h5py/_hl/dataset.py", line 47, in make_new_dset
    data = array_for_new_object(data, specified_dtype=dtype)
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/h5py/_hl/base.py", line 118, in array_for_new_object
    data = np.asarray(data, order="C", dtype=as_dtype)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (467,) + inhomogeneous part.
