Traceback (most recent call last):
  File "/home/pranavsatheesh/host_galaxies/py_files/population_sort_by_mergers.py", line 294, in <module>
    pop_gen.save_population_to_file(population_file_path)
  File "/home/pranavsatheesh/host_galaxies/py_files/population_sort_by_mergers.py", line 161, in save_population_to_file
    with h5py.File(outfilename, 'w') as f:
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/h5py/_hl/files.py", line 561, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/blue/lblecha/pranavsatheesh/.conda/envs/hfrl/lib/python3.10/site-packages/h5py/_hl/files.py", line 241, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 122, in h5py.h5f.create
FileNotFoundError: [Errno 2] Unable to synchronously create file (unable to open file: name = 'home/pranavsatheesh/host_galaxies/data/population_files/population_sort_gas-100_dm-100_star-100_bh-001.hdf5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242)
